"""
Detection services module for SatQuery.
Provides satellite class vocabulary, presets, class-specific thresholds,
label normalization, geometry validation, and detection formatting.
"""

from .vocabulary import (
    SATELLITE_CLASSES,
    ANALYSIS_PRESETS,
    ABSTRACT_CONCEPTS,
    DEFAULT_CLASS_THRESHOLDS,
    ClassThreshold,
    normalize_label,
    sanitize_prompt,
    map_score_to_confidence_level,
    compute_relative_location,
    format_detection,
    filter_and_format_detections,
    remove_duplicate_detections,
    box_iou,
)

from .tiler import (
    TILE_SIZE,
    TILE_OVERLAP,
    ENABLE_TILING,
    MIN_IMAGE_SIZE_FOR_TILING,
    MAX_TILES,
    should_tile_image,
    calculate_tile_grid,
    iter_tiles,
    generate_tiles,
    tile_bbox_to_global,
    format_tile_metadata,
)

from .nms import (
    DEFAULT_NMS_IOU_THRESHOLD,
    DEFAULT_CLASS_NMS_THRESHOLDS,
    get_class_nms_threshold,
    calculate_iou,
    apply_class_nms,
    get_deduplication_stats,
)

from .segmentation import (
    SAM2_AVAILABLE,
    SAM2_BACKEND,
    ENABLE_SEGMENTATION,
    DEFAULT_SEGMENTABLE_CLASSES,
    CLASS_OVERLAY_COLORS,
    is_class_segmentable,
    mask_to_rle,
    mask_to_polygon,
    compute_mask_bounds,
    compute_mask_area,
    generate_overlay_preview,
    segment_detections,
    get_sam2_predictor,
)

from .land_cover import (
    LandCoverAnalyzer,
    calculate_land_cover,
    DEFAULT_CATEGORY_PRIORITY,
    LABEL_TO_CATEGORY,
    LAND_COVER_COLORS,
    map_label_to_category,
)

from .verifier import (
    VERIFIER_AVAILABLE,
    ENABLE_VERIFICATION,
    VERIFICATION_THRESHOLD,
    DEFAULT_VERIFICATION_CLASSES,
    CLASS_NEGATIVE_ALTERNATIVES,
    crop_detection_box,
    get_alternatives_for_class,
    verify_detection,
    verify_detections,
    get_verifier,
)

__all__ = [
    "SATELLITE_CLASSES",
    "ANALYSIS_PRESETS",
    "ABSTRACT_CONCEPTS",
    "DEFAULT_CLASS_THRESHOLDS",
    "ClassThreshold",
    "normalize_label",
    "sanitize_prompt",
    "map_score_to_confidence_level",
    "compute_relative_location",
    "format_detection",
    "filter_and_format_detections",
    "remove_duplicate_detections",
    "box_iou",
    "TILE_SIZE",
    "TILE_OVERLAP",
    "ENABLE_TILING",
    "MIN_IMAGE_SIZE_FOR_TILING",
    "MAX_TILES",
    "should_tile_image",
    "calculate_tile_grid",
    "iter_tiles",
    "generate_tiles",
    "tile_bbox_to_global",
    "format_tile_metadata",
    "DEFAULT_NMS_IOU_THRESHOLD",
    "DEFAULT_CLASS_NMS_THRESHOLDS",
    "get_class_nms_threshold",
    "calculate_iou",
    "apply_class_nms",
    "get_deduplication_stats",
    "SAM2_AVAILABLE",
    "SAM2_BACKEND",
    "ENABLE_SEGMENTATION",
    "DEFAULT_SEGMENTABLE_CLASSES",
    "CLASS_OVERLAY_COLORS",
    "is_class_segmentable",
    "mask_to_rle",
    "mask_to_polygon",
    "compute_mask_bounds",
    "compute_mask_area",
    "generate_overlay_preview",
    "segment_detections",
    "get_sam2_predictor",
    "LandCoverAnalyzer",
    "calculate_land_cover",
    "DEFAULT_CATEGORY_PRIORITY",
    "LABEL_TO_CATEGORY",
    "LAND_COVER_COLORS",
    "map_label_to_category",
    "VERIFIER_AVAILABLE",
    "ENABLE_VERIFICATION",
    "VERIFICATION_THRESHOLD",
    "DEFAULT_VERIFICATION_CLASSES",
    "CLASS_NEGATIVE_ALTERNATIVES",
    "crop_detection_box",
    "get_alternatives_for_class",
    "verify_detection",
    "verify_detections",
    "get_verifier",
]


